name: "Publish"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - main
jobs:
  neuron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build amp site 🔧
      run: |
